[build]
  # הגדרת ה-base directory עבור החלק של הקליינט
  base = "client"
  command = "npm run build"
  publish = "client/build"


[[redirects]]
  from = "/api/*"
  to = "/server/api/:splat"
  status = 200

[functions]
  # הגדרת תיקיית הפונקציות (הפונקציות של Node.js)
  directory = "server/functions"

[build.environment]
  CI = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
