[build]
  # הגדרת ה-base directory עבור החלק של הקליינט
  base = "client"
  command = "npm run build"
  publish = "build"


[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[functions]
  # הגדרת תיקיית הפונקציות (הפונקציות של Node.js)
  directory = "server/functions"

[build.environment]
  CI = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
